from music21 import *

#take in the bot_notes sequence generated by our model:
bot_notes = #TODO

#function to transform a bot_note to a music21 note:
def noteOf(bot_note):
    pass
    #TODO

#create the final output sequence to be played
bot_stream = stream.Stream()   
for bot_note in bot_notes:
    bot_stream.append(noteOf(bot_note))

#and now......... play it!
bot_stream.show('midi')
